# Generated by Django 4.1.3 on 2022-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='more',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
