# Generated by Django 4.1.3 on 2022-11-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
